fix: unit tests to verify execution across multiple versions of ffmpeg
nrkno/sofie-package-manager pull request #133
Opened 2024-02-02 17:28 UTC by Julusian

## About Me

## Other Information

## Status

- [ ] PR is ready to be reviewed.
- [x] The functionality has been tested by the author.
- [x] Relevant unit tests has been added / updated.
- [ ] Relevant documentation (code comments, [system documentation](https://nrkno.github.io/sofie-core/)) has been added / updated.

2024-02-06 08:44 UTC, nytamin requested changes
Main issue right now is that the unit tests are failing on Windows.

Minor issue: The commit messages should ideally not be "fix:..." since they doesn't affect the application behaviour. "chore: " would have been better.

2024-02-06 08:44 UTC, nytamin commented on package.json
> +        "test:fetch-ffmpeg": "node scripts/fetch-ffmpeg.mjs",
It would be a bit easier to read if this was named "test:prepare" or similar

2024-02-06 08:44 UTC, nytamin commented on scripts/fetch-ffmpeg.mjs
> +				if (process.platform === 'win32') {
I added a separate algo for windows here, as `unzip` isn't a windows command.

2024-02-06 09:56 UTC, Julusian commented on shared/packages/worker/src/__tests__/ffmpegHelper.ts
> +	const ffmpegRootPath = path.join(__dirname, '../../../../../.ffmpeg')
It is doing that already. I'll move the loading of that json file to down here instead of being at the top of the file

2024-02-06 15:48 UTC, Julusian commented
> Main issue right now is that the unit tests are failing on Windows.

The tests will be fixed by #132.
I don't think this should be blocked on waiting for that PR to be ready, as this simply revealing a pretty major bug that slipped in due to lacking this test coverage, it doesn't make package-manager any more or less broken than before.

> Minor issue: The commit messages should ideally not be "fix:..." since they doesn't affect the application behaviour. "chore: " would have been better.

I've updated the title. I will do a squash and merge when it is approved, so that change will apply to the commit too.

2024-02-07 12:09 UTC, nytamin approved these changes
I'm happy with this PR now.
I would like us to merge this at the same time as #132 though, so we don't block the `develop` branch with failing unit tests more than necessary.

2024-02-12 10:30 UTC, merged